version: '3'
services:
  # Teedy Application
  teedy-server:
    image: sismics/docs:v1.10
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DOCS_BASE_URL: "https://docs.example.com"
      DOCS_ADMIN_EMAIL_INIT: "admin@example.com"
      DOCS_ADMIN_PASSWORD_INIT: "$$2a$$05$$PcMNUbJvsk7QHFSfEIDaIOjk1VI9/E7IPjTKx.jkjPxkx2EOKSoPS"
    volumes:
      - ./docs/data:/data
      - type: bind 
        source: C:\Users\dell xps\Documents\Final year projects\Fawazat Software\docs\docs-web\src\main\webapp\src 
        target: /usr/share/nginx/html/src
        consistency: delegated # or cached (depending on your needs)